'use client';
import Link from 'next/link';
import { useRouter, useSearchParams } from 'next/navigation';
import { useEffect, useState } from 'react';
import { ArrowRight, CalendarDays, Check, ChevronRight, Eye, EyeOff, Heart, HelpCircle, LogOut, Mail, Settings, ShieldCheck, Star, UserRound } from 'lucide-react';
import { safeReturn } from '@/lib/customer';
import { experiences } from '@/lib/catalog';
import { useCustomer } from './CustomerProvider';
import { Back, Gate, PageHeading, Photo } from './UI';
export function AuthPage({ register = false }: { register?: boolean }) {
  const router = useRouter(); const params = useSearchParams(); const { login, register: createAccount, ready } = useCustomer();
  const next = safeReturn(params.get('next')); const [name, setName] = useState(''); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [show, setShow] = useState(false); const [error, setError] = useState('');
  const submit = (event: React.FormEvent) => { event.preventDefault(); setError(''); const message = register ? createAccount(name, email, password) : login(email, password); if (message) setError(message); else router.replace(next); };
  return <div className="auth-layout"><aside className="auth-story"><Photo src={experiences[1].image} alt="Explore the green landscape around Sigiriya" sizes="(max-width: 900px) 100vw, 50vw" priority/><div><img src="/brand/buddy-mark.svg" alt="" width="76" height="76"/><h2>Good company.<br/>Great discoveries.</h2><p>A little curiosity can lead somewhere wonderful.</p><span>TravelBuddy · Your next story starts here.</span></div></aside><section className="auth-form-section"><div className="auth-form-inner"><p className="eyebrow">Your travel space</p><h1>{register ? 'Let’s start somewhere.' : 'Good to see you again.'}</h1><p>{register ? 'Save your discoveries, book your experiences and keep it all together.' : 'Your saved ideas and next adventures are waiting.'}</p><form onSubmit={submit} className="auth-form">{register && <label className="field">Your name<input autoComplete="name" value={name} onChange={event => setName(event.target.value)} required minLength={2} maxLength={80} placeholder="Alex Morgan"/></label>}<label className="field">Email address<input type="email" value={email} onChange={event => setEmail(event.target.value)} required autoComplete="email" placeholder="you@example.com" maxLength={120}/></label><label className="field">Password<div className="password-input"><input type={show ? 'text' : 'password'} value={password} onChange={event => setPassword(event.target.value)} autoComplete="off" placeholder="Enter your password" required/><button type="button" aria-label={show ? 'Hide password' : 'Show password'} onClick={() => setShow(value => !value)}>{show ? <EyeOff size={18}/> : <Eye size={18}/>}</button></div></label>{error && <p className="error-message" role="alert">{error}</p>}<button className="button button-primary button-wide" disabled={!ready}>{register ? 'Create customer account' : 'Sign in'}<ArrowRight size={18}/></button></form><p className="auth-switch">{register ? 'Already have a customer account?' : 'New to TravelBuddy?'} <Link href={`${register ? '/login' : '/register'}?next=${encodeURIComponent(next)}`}>{register ? 'Sign in' : 'Create an account'}</Link></p></div></section></div>;
}
export function AccountPage() { return <Gate><AccountContent/></Gate>; }
function AccountContent() { const { user, data, logout } = useCustomer(); const router = useRouter(); const links = [{ href: '/bookings', icon: CalendarDays, label: 'Your bookings', detail: `${data.bookings.filter(b => b.owner === user!.id).length} bookings` }, { href: '/saved', icon: Heart, label: 'Saved experiences', detail: `${(data.saved[user!.id] ?? []).length} ideas for later` }, { href: '/reviews', icon: Star, label: 'Your reviews', detail: 'Stories from your completed experiences' }, { href: '/account/settings', icon: Settings, label: 'Account settings', detail: 'Your name and display preferences' }, { href: '/support', icon: HelpCircle, label: 'Help & policies', detail: 'Booking and cancellation support' }]; return <div className="page-width account-page"><PageHeading eyebrow="Your travel space" title={`Hello, ${user!.name.split(' ')[0]}.`} text="A little curiosity. Everything in one place."/><div className="account-profile"><div className="account-avatar">{user!.name.split(' ').map(n => n[0]).slice(0, 2).join('')}</div><div><h2>{user!.name}</h2><p>{user!.email}</p></div></div><div className="account-links">{links.map(({ icon: Icon, ...link }) => <Link key={link.href} href={link.href}><span className="account-link-icon"><Icon size={21}/></span><div><strong>{link.label}</strong><small>{link.detail}</small></div><ChevronRight size={19}/></Link>)}</div><button className="button button-secondary logout-button" onClick={() => { logout(); router.replace('/'); }}><LogOut size={18}/>Sign out</button></div>; }
export function SettingsPage() { return <Gate><SettingsContent/></Gate>; }
function SettingsContent() {
  const { user, updateName } = useCustomer(); const [name, setName] = useState(user!.name); const [theme, setTheme] = useState('light'); const [message, setMessage] = useState('');
  useEffect(() => { setTheme(document.documentElement.dataset.theme ?? 'light'); }, []);
  const changeTheme = (value: string) => { setTheme(value); document.documentElement.dataset.theme = value; try { localStorage.setItem('travelbuddy-v1.1-theme', value); } catch { setMessage('Display preference will last only while this page is open.'); } };
  return <div className="page-width settings-page standard-page"><Back href="/account" label="Your account"/><PageHeading title="A space that feels like you." text="Simple details for your customer account."/><form className="settings-panel" onSubmit={event => { event.preventDefault(); updateName(name); setMessage('Your name is saved.'); }}><h2>Personal details</h2><label className="field">Your name<input value={name} onChange={event => setName(event.target.value)} required minLength={2} maxLength={80} autoComplete="name"/></label><label className="field">Email address<input type="email" value={user!.email} readOnly/></label><button className="button button-primary">Save changes <Check size={17}/></button></form><section className="settings-panel"><h2>Display</h2><p>Choose a comfortable view for browsing.</p><div className="segmented"><button className={theme === 'light' ? 'active' : ''} aria-pressed={theme === 'light'} onClick={() => changeTheme('light')}>Light</button><button className={theme === 'dark' ? 'active' : ''} aria-pressed={theme === 'dark'} onClick={() => changeTheme('dark')}>Dark</button></div></section>{message && <p className="inline-note" role="status">{message}</p>}</div>;
}
export function SupportPage() { const answers = [{ title: 'How do I book an experience?', text: 'Choose an experience, select an option, date, time and traveler count, then add it to your cart. Review your details and cancellation policy before confirming.' }, { title: 'What can I find on Explore?', text: 'Search experiences by destination, category, date, price and duration. Use Live availability to find offers with an available next slot, or browse the map.' }, { title: 'Can I cancel a booking?', text: 'Experiences marked Free cancellation allow cancellation until 24 hours before the start. Check your booking details for the applicable policy.' }, { title: 'How can I write a review?', text: 'Open Your reviews to rate a completed booking and share your experience. Each booking can be reviewed once.' }, { title: 'How are prices calculated?', text: 'Prices are shown in USD per person. Your selected option and traveler count determine the total shown before confirmation.' }]; return <div className="page-width support-page standard-page"><Back/><PageHeading eyebrow="A little help along the way" title="Travel with a clearer picture." text="Answers about experiences, bookings and cancellation policies."/><div className="support-content">{answers.map(item => <details key={item.title}><summary>{item.title}</summary><p>{item.text}</p></details>)}</div></div>; }
