import assert from 'node:assert/strict';
import { existsSync, readdirSync } from 'node:fs';
import path from 'node:path';
import { experiences } from '../src/lib/catalog';
import { addDays, availableSlots, canReview, cancelAllowed, emptyState, filteredExperiences, formatDate, itemPrice, nextAvailable, restoreState, safeReturn, today, validDate, validateCart, validateReview } from '../src/lib/customer';
let checks = 0;
function check(name: string, body: () => void) { body(); checks++; console.log(`PASS ${name}`); }
const monday = new Date('2026-10-05T04:30:00Z'); // 10:00 in Sri Lanka
const state = emptyState(monday);
const booking = state.bookings[0];
const cart = { id: 'test-cart', experienceId: 'colombo-food', option: 0, date: '2026-10-06', time: '17:30', travelers: 2 };
check('Sri Lanka date and midnight rollover', () => { assert.equal(today(monday), '2026-10-05'); assert.equal(today(new Date('2026-10-05T19:00:00Z')), '2026-10-06'); });
check('Calendar validates real dates and handles month rollover', () => { assert.equal(validDate('2026-02-30'), false); assert.equal(validDate('2028-02-29'), true); assert.equal(addDays('2026-10-31', 1), '2026-11-01'); });
check('Schedule excludes past dates, past times and closed Sundays', () => { assert.deepEqual(availableSlots('colombo-food', '2026-10-04', 0, 1, [], monday), []); assert.deepEqual(availableSlots('colombo-food', '2026-10-11', 0, 1, [], monday), []); assert.deepEqual(availableSlots('colombo-food', '2026-10-05', 0, 1, [], new Date('2026-10-05T14:00:00Z')), []); });
check('Schedule rejects bad date, option, count and out-of-range bookings', () => { assert.deepEqual(availableSlots('colombo-food', '2026-02-30', 0, 1, [], monday), []); assert.deepEqual(availableSlots('colombo-food', cart.date, 99, 1, [], monday), []); assert.deepEqual(availableSlots('colombo-food', cart.date, 0, 0, [], monday), []); assert.deepEqual(availableSlots('colombo-food', cart.date, 0, 1.5, [], monday), []); assert.deepEqual(availableSlots('colombo-food', addDays(today(monday), 181), 0, 1, [], monday), []); });
check('Live Now advances to the actual next date when today has ended', () => { const slot = nextAvailable('colombo-food', 0, 1, [], new Date('2026-10-05T14:00:00Z')); assert.equal(slot?.date, '2026-10-06'); assert.equal(slot?.time, '17:30'); });
check('Committed capacity and cart capacity are both enforced', () => { const busy = { ...booking, ...cart, id: 'busy', travelers: 11, status: 'Upcoming' as const }; assert.equal(availableSlots('colombo-food', cart.date, 0, 2, [busy], monday).includes('17:30'), false); assert.ok(validateCart([{ ...cart, travelers: 8 }, { ...cart, id: 'other', travelers: 5 }], [], monday)); assert.equal(validateCart([cart], [], monday), ''); });
check('Cancelled bookings release capacity', () => { const cancelled = { ...booking, ...cart, travelers: 12, status: 'Cancelled' as const }; assert.equal(availableSlots('colombo-food', cart.date, 0, 2, [cancelled], monday).includes('17:30'), true); });
check('Option and traveler count determine totals', () => { assert.equal(itemPrice(cart), 84); assert.equal(itemPrice({ ...cart, option: 1, travelers: 3 }), 288); });
check('Reviews require ownership and completion', () => { assert.equal(canReview(booking, 'customer-demo', []), true); assert.equal(canReview(booking, 'other-customer', []), false); assert.equal(canReview({ ...booking, status: 'Upcoming' }, 'customer-demo', []), false); assert.equal(canReview({ ...booking, status: 'Cancelled' }, 'customer-demo', []), false); });
check('Reviews are once per completed booking with valid rating and text', () => { const review = { id: 'r', owner: booking.owner, bookingId: booking.id, experienceId: booking.experienceId, rating: 5, text: 'A thoughtful experience with clear information.', date: '2026-10-05' }; assert.equal(canReview(booking, booking.owner, [review]), false); assert.equal(validateReview(booking, booking.owner, [], 5, review.text), ''); assert.ok(validateReview(booking, booking.owner, [], 6, review.text)); assert.ok(validateReview(booking, booking.owner, [], 4, 'Short')); });
check('Cancellation respects 24-hour policy and package exclusions', () => { const future = { ...booking, ...cart, status: 'Upcoming' as const }; assert.equal(cancelAllowed(future, monday), true); assert.equal(cancelAllowed(future, new Date('2026-10-05T13:00:00Z')), false); assert.equal(cancelAllowed({ ...future, experienceId: 'nyc-skyline' }, monday), false); assert.equal(cancelAllowed(booking, monday), false); });
check('Price ranges apply both inclusive endpoints', () => { assert.deepEqual(filteredExperiences({ minPrice: 42, maxPrice: 68, sort: 'price-low' }).map(e => e.price), [42, 55, 68]); assert.equal(filteredExperiences({ minPrice: 80, maxPrice: 40 }).length, 0); assert.ok(filteredExperiences({ minPrice: 75 }).every(e => e.price >= 75)); });
check('Filters narrow data and sorting changes ordering', () => { assert.equal(filteredExperiences({ query: 'Colombo' }).length, 1); assert.equal(filteredExperiences({ category: 'Food & drink' }).length, 1); assert.ok(filteredExperiences({ maxPrice: 50 }).every(e => e.price <= 50)); assert.ok(filteredExperiences({ cancellation: true }).every(e => e.freeCancellation)); assert.equal(filteredExperiences({ live: true }).length, 3); assert.equal(filteredExperiences({ duration: 'short' }).some(e => e.duration === '8 hours'), false); const result = filteredExperiences({ sort: 'price-low' }); assert.ok(result.every((e, i) => i === 0 || e.price >= result[i - 1].price)); });
check('Auth return URLs stay on the local customer app', () => { assert.equal(safeReturn('//evil.example'), '/'); assert.equal(safeReturn('/\\evil.example'), '/'); assert.equal(safeReturn('/login?next=/cart'), '/'); assert.equal(safeReturn('/experience/colombo-food?date=2026-10-06'), '/experience/colombo-food?date=2026-10-06'); });
check('Local fixtures recover corrupted storage without persisting credentials', () => { assert.equal(restoreState('{bad-json').accounts[0].email, 'traveler@travelbuddy.demo'); assert.ok(!JSON.stringify(state).includes('demo123')); assert.equal(restoreState(JSON.stringify(state)).version, 1); });
check('Customer route inventory excludes all other phases and role portals', () => { const app = path.resolve('src/app'); for (const name of ['admin', 'supplier', 'guide-workspace', 'guide', 'advisor', 'partner', 'community', 'requests', 'trips', 'scan', 'api']) assert.equal(existsSync(path.join(app, name)), false, `${name} must not ship in V1.1`); assert.deepEqual(readdirSync(path.join(app, 'register')), ['page.tsx']); assert.ok(existsSync(path.join(app, 'reviews/page.tsx'))); });
check('Every catalog listing has a customer detail and valid option prices', () => { assert.ok(experiences.length > 0); experiences.forEach(e => { assert.ok(e.options.length); e.options.forEach(o => { assert.ok(o.price > 0); assert.ok(o.times.every(t => /^\d{2}:\d{2}$/.test(t))); }); }); });
console.log(`${checks} customer checks passed.`);
